---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school-prod
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - ../../base

patches:
  - path: patch-replicas.yaml


