apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: noakhali/school-app-employeeservice:2.0
          ports:
            - containerPort: 5003
              protocol: TCP
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: school-app-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: school-app-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: school-app-config
                  key: MONGO_DB
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: school-db-credentials
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: school-db-credentials
                  key: MONGO_PASSWORD
            