upstream frontend {
    server frontend:3000;
}
upstream studentservice {
    server studentservice:5001;
}
upstream teacherservice {
    server teacherservice:5002;
}
upstream employeeservice {
    server employeeservice:5003;
}

server {
    listen 80;
    location /studentservice {
        rewrite /studentservice/(.*) /$1 break;
        proxy_pass http://studentservice;
    }
    location /teacherservice {
        rewrite /teacherservice/(.*) /$1 break;
        proxy_pass http://teacherservice;
    }
    location /employeeservice {
        rewrite /employeeservice/(.*) /$1 break;
        proxy_pass http://employeeservice;
    }
    
    location / {
        proxy_pass http://frontend; 
    }
}
