---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school-dev
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - school-ingress-regex.yaml
  - school-ingress-prefix.yaml
  - ../../base

patches:
  - path: patch-replicas.yaml
  # - path: configmap.yaml
  # - path: secret.yaml
  # - path: ingress.yaml

